### ISSUE TITLE
nice typo

### ISSUE THREAD

**Issue by wowjeeez** [HypeLevels/hippobot#1]
https://github.com/HypeLevels/hippobot/blob/f1df39cf1bf95584e7375f11013687d147a237e8/src/buttons/delete.ts#L10

**Comment by HypeLevels** [comment]
It's not a typo, TypeScript yells if you name a class delete, I know I should instead follow class naming conventions and name it Delete.

**Comment by wowjeeez** [comment]
yea thats the other thing that I wanted to point out
